//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Servicios.Servicio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CompletarchklistBoxPermisosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarChequeadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransaccionABOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Servicios.Properties.Settings.Default.Servicios_Servicio_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CompletarchklistBoxPermisosCompletedEventHandler CompletarchklistBoxPermisosCompleted;
        
        /// <remarks/>
        public event ConsultarChequeadosCompletedEventHandler ConsultarChequeadosCompleted;
        
        /// <remarks/>
        public event TransaccionABCompletedEventHandler TransaccionABCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CompletarchklistBoxPermisos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompletarchklistBoxPermisos() {
            object[] results = this.Invoke("CompletarchklistBoxPermisos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CompletarchklistBoxPermisosAsync() {
            this.CompletarchklistBoxPermisosAsync(null);
        }
        
        /// <remarks/>
        public void CompletarchklistBoxPermisosAsync(object userState) {
            if ((this.CompletarchklistBoxPermisosOperationCompleted == null)) {
                this.CompletarchklistBoxPermisosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompletarchklistBoxPermisosOperationCompleted);
            }
            this.InvokeAsync("CompletarchklistBoxPermisos", new object[0], this.CompletarchklistBoxPermisosOperationCompleted, userState);
        }
        
        private void OnCompletarchklistBoxPermisosOperationCompleted(object arg) {
            if ((this.CompletarchklistBoxPermisosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompletarchklistBoxPermisosCompleted(this, new CompletarchklistBoxPermisosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarChequeados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarChequeados(int id) {
            object[] results = this.Invoke("ConsultarChequeados", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarChequeadosAsync(int id) {
            this.ConsultarChequeadosAsync(id, null);
        }
        
        /// <remarks/>
        public void ConsultarChequeadosAsync(int id, object userState) {
            if ((this.ConsultarChequeadosOperationCompleted == null)) {
                this.ConsultarChequeadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarChequeadosOperationCompleted);
            }
            this.InvokeAsync("ConsultarChequeados", new object[] {
                        id}, this.ConsultarChequeadosOperationCompleted, userState);
        }
        
        private void OnConsultarChequeadosOperationCompleted(object arg) {
            if ((this.ConsultarChequeadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarChequeadosCompleted(this, new ConsultarChequeadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransaccionAB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransaccionAB(string permisos, int idUsuario) {
            this.Invoke("TransaccionAB", new object[] {
                        permisos,
                        idUsuario});
        }
        
        /// <remarks/>
        public void TransaccionABAsync(string permisos, int idUsuario) {
            this.TransaccionABAsync(permisos, idUsuario, null);
        }
        
        /// <remarks/>
        public void TransaccionABAsync(string permisos, int idUsuario, object userState) {
            if ((this.TransaccionABOperationCompleted == null)) {
                this.TransaccionABOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransaccionABOperationCompleted);
            }
            this.InvokeAsync("TransaccionAB", new object[] {
                        permisos,
                        idUsuario}, this.TransaccionABOperationCompleted, userState);
        }
        
        private void OnTransaccionABOperationCompleted(object arg) {
            if ((this.TransaccionABCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransaccionABCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CompletarchklistBoxPermisosCompletedEventHandler(object sender, CompletarchklistBoxPermisosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompletarchklistBoxPermisosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompletarchklistBoxPermisosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ConsultarChequeadosCompletedEventHandler(object sender, ConsultarChequeadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarChequeadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarChequeadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TransaccionABCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591